spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lead_consult
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: parola123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true